data <- read.table("household_power_consumption.txt", sep = ";", skip = 66637, nrow = 2880, col.names = colnames(read.table("household_power_consumption.txt", sep = ";", nrow = 1, header = TRUE)))
data$date_time <- paste(data$Date, data$Time)
data$date_time <- strptime(data$date_time, "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
with(data, {
    plot(data[, c("date_time", "Global_active_power")], type="l", xlab = "", ylab = "Global Active Power")
    plot(data[, c("date_time", "Voltage")], type="l", xlab = "datetime", ylab = "Voltage")
    plot(data[, c("date_time","Sub_metering_1")], type = "l", xlab = "", ylab = "Energy sub metering")
    lines(data[, c("date_time","Sub_metering_2")], type = "l", col = "RED")
    lines(data[, c("date_time","Sub_metering_3")], type = "l", col = "BLUE")
    legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black", "red", "blue"), bty = "n")
    plot(data[, c("date_time", "Global_reactive_power")], type="l", xlab = "datetime")
    })
dev.off()